# Inspired by https://gist.github.com/rydmike/fdb53ddd933c37d20e6f3188a936cd4c
include: all_lint_rules.yaml
analyzer:
  exclude:
    - "**/*.g.dart"

  # For more information see: https://dart.dev/tools/analysis
  language:
  errors:
    # Without ignore here, we cause import of all_lint_rules to warn, because some rules conflict.
    # We explicitly enable conflicting rules and are fixing the conflicts in this file.
    # Put it to warning temporarily if you need to troubleshoot lint rule settings.
    included_file_warning: ignore

    # Treat missing required parameters as an error, not as a hint or a warning.
    missing_required_param: error

    # Treat missing returns as an error, not as a hint or a warning.
    missing_return: error

    # A record literal with exactly one positional field requires a trailing comma.
    record_literal_one_positional_no_trailing_comma: error

    # Invocation collection methods with arguments of unrelated types.
    collection_methods_unrelated_type: error

    # Invocation of equality operator == with references of unrelated types.
    unrelated_type_equality_checks: error

    # Allow having TODOs in the code.
    todo: ignore

# Explicitly disable only the rules we do not want.
linter:
  rules:
    always_put_control_body_on_new_line: false
    always_specify_types: false
    # Violates Effective Dart "PREFER annotating with dynamic instead of letting inference fail", it
    # also conflicts with strong mode disabling `implicit-dynamic`. Turning it OFF.
    avoid_annotating_with_dynamic: false
    avoid_classes_with_only_static_members: false
    avoid_types_on_closure_parameters: false
    close_sinks: false
    # Turn on if you're creating a library for other developers
    diagnostic_describe_all_properties: false
    document_ignores: false
    no_default_cases: false
    omit_local_variable_types: false
    omit_obvious_local_variable_types: false
    # I like this, but it lints 'fromJson' constructors
    prefer_constructors_over_static_methods: false
    prefer_double_quotes: false
    prefer_null_aware_method_calls: false
    prefer_expression_function_bodies: false
    discarded_futures: false
    # not used because of false positives in parameters
    prefer_final_parameters: false
    prefer_int_literals: false
    prefer_relative_imports: false
    public_member_api_docs: false
    specify_nonobvious_local_variable_types: false
    require_trailing_commas: false
    unnecessary_final: false
    # Not used because of this issue https://github.com/dart-lang/linter/issues/3286
    use_decorated_box: false