name: wikipedia_api
description: Shared models and wrapped http calls for Wikipedia clients
version: 0.0.1
resolution: workspace
publish_to: none
environment:
  sdk: ^3.7.0-209.1.beta

# Add regular dependencies here.
dependencies:
  http: ^1.2.2
  json_annotation: ^4.9.0
  logging: ^1.3.0
dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  lints: ^5.0.0
  test: ^1.24.0


