name: cli
description: A sample command-line application that fetches articles from Wikipedia.
version: 0.0.1
resolution: workspace
publish_to: none

environment:
  sdk: ^3.7.0-209.1.beta

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  io: ^1.0.5
  shared:
    path: ../shared

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
