name: wikipedia_cli
description: A sample command-line application with basic argument parsing.
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.7.0-209.1.beta

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  wikipedia_api:
    path: ../wikipedia_api

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
